### ISSUE TITLE
Add git tag/release

### ISSUE THREAD

**Issue by sanposhiho** [mercari/testdeck#6]
Hi team. I want to this repository to be managed by tag/release.

reasons:

- little inconvenient for Go modules users
- dependabot is not aware of the update of the library

Is there any reason why this repository is not currently managed by those?

**Comment by sanposhiho** [comment]
Hello
any update?

**Comment by gmgchow** [comment]
Hi @sanposhiho , sorry for the late reply. I have added release tags so I will close this ticket. Thank you very much for your suggestion!

**Comment by sanposhiho** [comment]
very thanks 🙇
